### ISSUE TITLE
Issue 6 for Milestone 3: Training the model

### ISSUE THREAD

**Issue by 134668** [134668/BIproject#6]
- [x] Data Splitting
- [x] Bootstrapping
- [x] Cross Validation(basic, repeated or LOOCV)
- [x] Model training for either classification, regression, association or clustering(as applicable)
- [ ] Model Performance comparison using resamples(for classification and regression)
